server:
  port: 8088
spring:
  thymeleaf:
    cache: false
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-admin
  protocol:
    serialization: kryo
    port: 20884