spring:
  mail:
    username: 17639206656@163.com
    password: wstore1234
    host: smtp.163.com
  rabbitmq:
    addresses: 192.168.144.130
    port: 5672
    username: admin
    password: admin