server:
  port: 8095
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-item
  protocol:
    serialization: kryo
    port: 20888
#thymeleaf
spring:
  thymeleaf:
    cache: false
  redis:
      host: 192.168.144.133
      port: 6379
      database: 0
#购物车key
cart:
  #用户
  temp:
    key: UID
    time: 10
  #购物车分组
  group: CART_GROUP;