server:
  port: 8090
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-list
  protocol:
    serialization: kryo
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.144.133
    port: 6379
    database: 0