spring:
  datasource:
    url: jdbc:mysql://192.168.144.133:3306/wstore
    username: root
    password: root

dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-service-portal
  protocol:
    serialization: kryo
    port: 20886
###
pay:
  host:
    #支付结果同步返回地址
    return: http://localhost:8096/pay/result
    #支付结果异步返回地址
    notify: http://dc36d150.ngrok.io/pay/notify
    #支付宝网关
    gatway: https://openapi.alipaydev.com/gateway.do
  #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  appid: 2016092100560591
  #商户私钥，您的PKCS8格式RSA2私钥
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMkp1ejKEC60vVn++DFftNq0bsgPPkSTrfh+s4K2C7S5xZTVL7vPKtnZ2GFxnWPfPDVzhUVwjVyPb6SCvdOo+sEFhmWSztMhv7hB3gdCDL68RtHYpB6JQ0mtERR5CG1oV7HjSIFS6r4xsNzxF6dYJGBwFwAb2kuSEI1U9Z17R3QaWC/9T618xd0coff/TakGSX6DKf8lDERh7nx2DcA5fPUcdhggn215o0sUVecGuOAHAgy982YL+FbRYu+2JJQ7v2rEA5pLzh+qfqPuqw4Of/Di4BAcgu54OCoThQMaRh/nHJJ2jli0Yk/8/gVS2nCgBIwW2l6LyR4dCOJx72c72FAgMBAAECggEAEPQdxqlvQcre+oSvfj/IbzWY+C0VPRMX5p2d4Mhagjw8Pwj0WSgQnJ/Fv8ZJd21BWO3L/WAB0MbMAqNxptzJNxdBkhZvNKw2c78bW1amHfHxXreRVSGXvkBttofLBngY4SBjdYYYeuKJAMFYekxxycBOjBOpq5QoR8hyKYO6YCd8ekssWCDG9+y4JlN41fqMmpsMYwFxrnRCFBOtwSHHMAnqDSoTH5dL+uzseUWeQWw0HHTn1IMyWXiJfZe7KCymccsx4Qbq8z+RwNM8Tc0r9ZIaalVt341whqtZRWPZ+/Bl282WEbH26HKbsZO76WLPNSvQLJbVg/5YXHc4M7lqgQKBgQDaHz0B36x7sTr1tFWRzowi1LB8FAWrgLTzWlE0RiBjUd043d+L7VMkYdMcgmBCu7vAX5n+dVYek3WakJBL2MoFUPqkt7aqv6Dce2IMeke7AsdiuoCwQ/WsyCJ4mQEPmvyrZeWGnqlobrmpjzPXy+MDteuHQn2a8eEr8xu1HZP7qwKBgQCk+96X7BrC6yyXsDr/PiyYI1vDC/6ho8Nriq8ecBKcl9lIU06IFqdTB/S4uUZUH6mPWDj+gXYyJ4JFAeBwnMoVA3AxZSSdNKp5iq9blq4bRvZ4edAddPFRaclf0jr3PuW7oNBVWD3UkKdwzgoYzK7/8VAGw5SFSl8TrCjM/Z17jwKBgQCLTY4J507iBFNyXkSUBUSsbgd0htkEKgPms1TPPMYsiDjvu4uscto5jxxjxcQyenEzMBtKTqe8iVJ/bzoopoCHGquojQflTtMuXMJG08WB4wlxvUi4yf5Z5ctWF+l8jPA3irEm46ev4Z9DcgibFkSatxF/5fAQB9BV4EJezlAXVwKBgQCUnPTjcKCil+jxMqPSK5VL7f3IclOKEtQDWUdpaZa6S+ZDyhbha1aJ6o68ntgFCwhXwSaFyuRHRWOI+anMhs9ZomE7fVo/6aLuHMjc/ZwTohZ+a2vWPPLrXRkyIVNQR+3012USm4wGn87URCTANhAlKJ/nl+F/N4DxXZDbJlDnbQKBgHBYLnNzeiJkaxu35YSyY9e3cphpmRAFcEz54myboIK3w7iFqfnVcERmtZeZHpy63hXJLWeih4ipXPUl0152PEGiFC31o1gshhKtHF+337yAoMSyD9EpqJgAOmKHMC+O7y49hv8X4W0GbruvuxBaf88T45riRgXdS1Eumxdkk8Xu
  #支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5CLvffC+o+/FNKbo76gn8AiXFUFw3gg/PXVAib81KWApocKPUJCzRYptwxCef9eKj1wY3zSfpGjIR0I05FrV+3u3jG7Ga13rKLDM53qt7mM6HSDj0MGTjiKiS3BsfmIPn6YZMMFqzq6p5+FHDjwN0iHEj8ztJe6Fo4i3kqbBcRQVsa7UKByObmf2kqvy7ulOmzHjyioB3o5jMNtNE42cJrjeTNl/INMh1LIK7vTveFjxuPyiEK5MlciD82w7u4JeqnwYl39Qe5QmZN1kHNaQjLq9AgsU1H+hNcxAYj229MxJjj2oss32y7QWrhi2fdp7+kI0zCIVi1JEI63r4MewrwIDAQAB
