spring:
  datasource:
    url: jdbc:mysql://192.168.144.133:3306/wstore
    username: root
    password: root
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-service-cart
  protocol:
    serialization: kryo
server:
  port: 8082
logging:
  level:
    com.wstore.mapper: debug