spring:
  datasource:
    url: jdbc:mysql://192.168.144.133:3306/wstore
    username: root
    password: root
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-service-portal
  protocol:
    serialization: kryo
    port: 20887

logging:
  level:
    com.wstore.mapper: debug

##
last:
  time:
    #订单支付超时 m
    pay: 2
    #自动确认收货时间 d
    ship: 10