server:
  port: 8096

#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-list
  protocol:
    serialization: kryo
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.144.133
    port: 6379
    database: 0
  rabbitmq:
    addresses: 192.168.144.130
    port: 5672
    username: guest
    password: guest
#host
login:
  href: http://localhost:8100/login
pay:
  result: http://localhost:8096/order/center