server:
  port: 8083
#图片服务器
fdfs:
    so-timeout: 1501
    connect-timeout: 601
    thumb-image:
        width: 150
        height: 150
    tracker-list:
        - 192.168.144.131:22122
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-admin
  protocol:
    serialization: kryo
    port: 20884
  provider:
    timeout: 1200
#thymeleaf模板配置
spring:
  thymeleaf:
    cache: false
#regis
admin.login.key: ADMIN_KEYS
#登陆超时时间 -s
login.time.out: 600
#上传图片最大值 单位 MB
upload_picture_size: 3
#上传图片最小宽度
upload_picture_min_width: 50
#支持文件格式
upload_picture_format: jpg,png
#图片服务器
img_server_host: 192.168.144.131

