spring:
  mail:
    host: smtp.163.com
    username: 17639206656@163.com
    password: wstore1234

fdfs:
    so-timeout: 1501
    connect-timeout: 601
    thumb-image:
        width: 150
        height: 150
    tracker-list:
        - 192.168.144.131:22122