server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://192.168.144.133:3306/wstore
    username: root
    password: root
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-service-admin
  protocol:
    serialization: kryo
    port: 20884
  provider:
    timeout: 600
#pageHelper插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#分页配置
page:
  size: 10
  navigate: 5
logging:
  level:
    com.wstore.mapper: debug