server:
  port: 8085
#Dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-item
    qos-enable: false
  protocol:
    serialization: kryo
    port: 20887
#redis
spring:
  redis:
    host: 192.168.144.133
    port: 6379
    database: 2
  thymeleaf:
    cache: false
#redis item
item:
  product:
    key: ITEM_PRODUCT
  sku:
    key: ITEM_SKU