spring:
  datasource:
    url: jdbc:mysql://192.168.144.133:3306/wstore
    username: root
    password: root
  redis:
    host: 192.168.144.128
    port: 6379
    database: 0
  rabbitmq:
    addresses: 192.168.144.130
    username: guest
    password: guest
#dubbo
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-service-sso
  protocol:
    serialization: kryo
    port: 20879
logging:
  level:
    com.wstore.mapper: debug