server:
  port: 8100

#dubbo配置
dubbo:
  registry:
    address: zookeeper://192.168.144.130
    port: 2181
  application:
    name: wstore-web-sso
  protocol:
    serialization: kryo

#rabbitMQ
spring:
  rabbitmq:
    addresses: 192.168.144.130
    username: admin
    password: admin
  thymeleaf:
    cache: false
  redis:
      host: 192.168.144.133
      port: 6379
      database: 0

###
verify_code:
    key: VERIFY_CODE
    timeout: 300
    length: 5
verify_mail:
    key: VERIFY_MAIL
    timeout: 600
    length: 8
sso:
  key: UID
  timeout: 30

#首页地址
portal:
  host: http://localhost:8088